require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LibsController do

  # This should return the minimal set of attributes required to create a valid
  # Lib. As you add validations to Lib, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LibsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all libs as @libs" do
      lib = Lib.create! valid_attributes
      get :index, {}, valid_session
      assigns(:libs).should eq([lib])
    end
  end

  describe "GET show" do
    it "assigns the requested lib as @lib" do
      lib = Lib.create! valid_attributes
      get :show, {:id => lib.to_param}, valid_session
      assigns(:lib).should eq(lib)
    end
  end

  describe "GET new" do
    it "assigns a new lib as @lib" do
      get :new, {}, valid_session
      assigns(:lib).should be_a_new(Lib)
    end
  end

  describe "GET edit" do
    it "assigns the requested lib as @lib" do
      lib = Lib.create! valid_attributes
      get :edit, {:id => lib.to_param}, valid_session
      assigns(:lib).should eq(lib)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lib" do
        expect {
          post :create, {:lib => valid_attributes}, valid_session
        }.to change(Lib, :count).by(1)
      end

      it "assigns a newly created lib as @lib" do
        post :create, {:lib => valid_attributes}, valid_session
        assigns(:lib).should be_a(Lib)
        assigns(:lib).should be_persisted
      end

      it "redirects to the created lib" do
        post :create, {:lib => valid_attributes}, valid_session
        response.should redirect_to(Lib.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lib as @lib" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lib.any_instance.stub(:save).and_return(false)
        post :create, {:lib => {}}, valid_session
        assigns(:lib).should be_a_new(Lib)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lib.any_instance.stub(:save).and_return(false)
        post :create, {:lib => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lib" do
        lib = Lib.create! valid_attributes
        # Assuming there are no other libs in the database, this
        # specifies that the Lib created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lib.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lib.to_param, :lib => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lib as @lib" do
        lib = Lib.create! valid_attributes
        put :update, {:id => lib.to_param, :lib => valid_attributes}, valid_session
        assigns(:lib).should eq(lib)
      end

      it "redirects to the lib" do
        lib = Lib.create! valid_attributes
        put :update, {:id => lib.to_param, :lib => valid_attributes}, valid_session
        response.should redirect_to(lib)
      end
    end

    describe "with invalid params" do
      it "assigns the lib as @lib" do
        lib = Lib.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lib.any_instance.stub(:save).and_return(false)
        put :update, {:id => lib.to_param, :lib => {}}, valid_session
        assigns(:lib).should eq(lib)
      end

      it "re-renders the 'edit' template" do
        lib = Lib.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lib.any_instance.stub(:save).and_return(false)
        put :update, {:id => lib.to_param, :lib => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lib" do
      lib = Lib.create! valid_attributes
      expect {
        delete :destroy, {:id => lib.to_param}, valid_session
      }.to change(Lib, :count).by(-1)
    end

    it "redirects to the libs list" do
      lib = Lib.create! valid_attributes
      delete :destroy, {:id => lib.to_param}, valid_session
      response.should redirect_to(libs_url)
    end
  end

end
