source 'https://rubygems.org'

gem 'rails', '3.2.8'

#-*- coding: utf-8 -*-
source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'sqlite3', :groups => [:test, :development]
group :production do
	gem 'pg'
end

group :assets do
	#gem 'sass-rails', '~> 3.2.3'
	gem 'coffee-rails', '~> 3.2.1'
	#see https://github.com/sstephenson/execjs#readme for more supported runtimes
	#gem 'therubyracer'
	gem 'uglifier', '>= 1.0.3'

	#zobacz https://github.com/seyhunak/twitter-bootstrap-rails
	#gem 'twitter-bootstrap -rails'
end
gem 'jquery-rails'
gem 'json'

#łatwiejsze w użyciu formularze
#zobacz https://github.com/plataformatec/simple_form
gem 'simple_form'

group :development do
	#ładniejsze wypisywanie rekordów na konsoli
	#(zob. konfiguracja irb w ~/.irbrc)
	gem 'hirb'
	#bezproblemowe zapełnianie bazy danymi testowymi
	#https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md
	#gem 'factory_girl_rails', '~> 1.2'
	#gem 'faker'
	#gem 'populator'
	#wyłącza logowanie *assets pipeline*
	gem 'quiet_assets'
end

#alternatywa dla serwera Webrick
gem 'thin'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
